project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: false
  render:
    - "*.qmd"
    - "!fragments/"
  resources:
    - "class/"
    - "content/"
    - "project/"
    - "rubrics/"
    - "slides/"
    - "templates/"

website:
  title: EMSE 6035
  image: images/logo.png
  site-url: https://madd.seas.gwu.edu/2022-Fall/
  favicon: images/favicon.ico
  repo-url: https://github.com/emse-madd-gwu/2022-Fall
  repo-actions: [edit, issue]
  description: 'Course website for Fall 2022 semester of the EMSE course "Marketing Analytics for Design Decisions" at GWU'
  search:
    location: navbar
    type: overlay
    copy-button: true
  open-graph:
    locale: es_ES
    site-name: https://madd.seas.gwu.edu/
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/logo-square.png"
    card-style: summary
  navbar:
    background: primary
    left:
      - text: Home
        href: index.qmd
      - text: Syllabus
        href: syllabus.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: Class
        menu:
        - text: "Aug 31: Getting Started"
          href: class/1-getting-started.qmd
        - text: "Sep 07: Data Wrangling"
          href: class/2-data-wrangling.qmd
        - text: "Sep 14: RMarkdown & Plotting"
          href: class/3-rmarkdown-plotting.qmd
        - text: "Sep 21: Intro to formr"
          href: class/4-intro-to-formr.qmd
        - text: "Sep 28: No Class - Team Meetings"
        - text: "Oct 05: Conjoint Questions"
          href: class/5-conjoint-questions.qmd
        - text: "Oct 12: Utility Models"
          href: class/6-utility-models.qmd
        - text: "Oct 19: Optimization & MLE"
          href: class/7-optimization-mle.qmd
        - text: "Oct 26: Uncertainty"
          href: class/8-uncertainty.qmd
        - text: "Nov 02: DOE & Power Analysis"
          href: class/9-doe-power-analysis.qmd
        - text: "Nov 09: WTP & Simulation"
          href: class/10-wtp-simulation.qmd
        - text: "Nov 16: Heterogeneity"
          href: class/11-heterogeneity.qmd
        - text: "Nov 23: Thanksgiving - no class"
        - text: "Nov 30: Class Review"
          href: class/12-class-review.qmd
        - text: "Dec 07: Exam Solutions"
          href: class/13-exam-solutions.qmd
        - text: "Dec 14: Final Presentations"
      - text: "Assignments"
        menu:
        - text: "Self Assessment (optional)"
          href: hw/0-self-assessment.qmd
        - text: "Aug 31: Data Wrangling (Due 09/07)"
          href: hw/1-data-wrangling.qmd
        - text: "Sep 07: Plotting (Due 09/14)"
          href: hw/2-plotting.qmd
        - text: "Sep 14: formr (Due 09/21)"
          href: hw/3-formr.qmd
        - text: "Oct 05: Utility Models (Due 10/12)"
          href: hw/4-utility-models.qmd
        - text: "Oct 12: Estimation (Due 10/19)"
          href: hw/5-estimation.qmd
        - text: "Oct 19: Uncertainty (Due 10/26)"
          href: hw/6-uncertainty.qmd
        - text: "Oct 26: Design of Experiment (Due 11/02)"
          href: hw/7-design-of-experiment.qmd
        - text: "Nov 02: WTP & Simulation (Due 11/09)"
          href: hw/8-wtp-simulation.qmd
        - text: "Nov 09: Heterogeneity (Due 11/16)"
          href: hw/9-heterogeneity.qmd
        - text: "Nov 30: Exam (Due 12/05)"
          href: hw/10-exam.qmd
      - text: Project
        menu:
        - text: "Project Overview"
          href: project/0-overview.qmd
        - text: Proposal (Due Sep 26)
          href: project/1-proposal.qmd
        - text: Survey Plan (Due Oct 05)
          href: project/2-survey-plan.qmd
        - text: Pilot Survey (Due Oct 15)
          href: project/3-pilot-survey.qmd
        - text: Pilot Analysis (Due Nov 07)
          href: project/4-pilot-analysis.qmd
        - text: Final Survey (Due Nov 19)
          href: project/5-final-survey.qmd
        - text: Final Analysis (Due Dec 13)
          href: project/6-final-analysis.qmd
        - text: Final Presentation (Due Dec 15)
          href: project/7-final-presentation.qmd
      - text: Help
        menu:
        - text: Schedule a call w/Prof. Helveston
          icon: person
          href: help/https://jhelvy.appointlet.com/b/professor-helveston
        - text: Example Projects
          icon: file-earmark-medical
          href: help/example-projects.qmd
        - text: Course Software
          icon: hdd
          href: help/course-software.qmd
        - text: Getting Help
          icon: question-circle
          href: help/getting-help.qmd
        - text: Visualizing Data
          icon: bar-chart
          href: help/visualizing-data.qmd
        - text: Programming in R
          icon: terminal
          href: help/programming.qmd
        - text: R Markdown
          icon: pen
          href: help/rmarkdown.qmd
        - text: Other
          icon: chevron-expand
          href: help/other.qmd
      - icon: slack
        href: https://emse-madd-f22.slack.com
    right:
    - icon: list
      menu:
      - text: About
        icon: question-circle
        href: about.qmd
      - text: License
        icon: award
        href: LICENSE.qmd
      - text: Contact
        icon: envelope
        href: mailto:jph@gwu.edu
      - text: Source files
        icon: github
        href: https://github.com/emse-madd-gwu/2022-Fall/
  page-footer:
    center:
      - text: '© 2021 John Paul Helveston <a href="LICENSE.html"><i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-by"></i><i class="fab fa-creative-commons-sa"></i></a><br><i class="far fa-calendar-alt"></i> {{< var weekday >}} | <i class="far fa-clock"></i> {{< var time >}} | <a href="{{< var room_url >}}"><i class="fa fa-map-marker-alt"></i> {{< var room >}}</a> | <a href="https://www.jhelvy.com"><i class="fas fa-user"></i> Dr. John Paul Helveston</a> | <a href="mailto:jph@gwu.edu"><i class="fas fa-envelope"></i> jph@gwu.edu</a> | <a href="{{< var repo >}}"><i class="fab fa-github"></i></a>'

format:
  html:
    theme: united
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    include-in-header: "_includes/header.html"
