---
title: Course Schedule
---

```{r child = file.path("fragments", "setup.qmd")}
```

```{r echo=FALSE}
# Setup some common values
fa <- list(
  quiz        = '[<i class="fas fa-edit"></i>]',
  assignments = '[<i class="fas fa-book-reader"></i>]',
  class       = '[<i class="fas fa-laptop-code"></i>]',
  project     = '[<i class="fas fa-pencil-ruler"></i>]'
)

# Make the schedule data frame
schedule <- get_schedule() %>%
  mutate(
    date_raw = date,
    date = format(date, format = "%b %d"),
    assign_due = format(assign_due, format = "%b %d"),
    project_due = format(project_due, format = "%b %d"),
    # Replace NA values with ""
    class_desc = ifelse(is.na(class_desc), "", class_desc),
    project_desc = ifelse(is.na(project_desc), "", project_desc),
    # Build markdown
    stub = ifelse(
      is.na(stub), "",
      paste0(fa$class, "(c", week, "-",  stub, ".html)")),
    class = ifelse(
      is.na(class), "",
      paste0("**", class, "**<br>", class_desc)),
    class = paste(stub, class, sep = " "),
    projects = ifelse(
      is.na(project), NA,
      paste0("**", project, "**<br>", project_desc)),
    assignments = ifelse(
      is.na(assign_name), NA,
      paste0(
        fa$assignments, "(a", assign_n, "-", assign_url, ".html) **",
        assign_name, "**<br>Due ", assign_due)),
    project = ifelse(
      is.na(project_name), NA,
      paste0(
        fa$project, "(p", project_n, "-", project_url, ") **", 
        project_name, "**<br>Due ", project_due))
  )

highlight <- which(Sys.Date() > schedule$date_raw)

# Make the final schedule
names(schedule) <- str_to_title(names(schedule))
schedule %>%
  select(-Date_raw) %>% 
  rename(` ` = Project) %>%
  select(Week, Date, Quiz, Class, Projects, Assignments, ` `) %>%
  kable(format = 'html', escape = FALSE,
        align = c('c', 'c', 'c', 'l', 'l', 'l', 'l')) %>%
  kable_styling(full_width = F, bootstrap_options = c("striped", "hover")) %>%
  column_spec(column = 4, width = '16em') %>% 
  column_spec(column = 5, width = '16em') %>% 
  column_spec(column = 6, width = '10em') %>% 
  column_spec(column = 7, width = '10em')
  # row_spec(highlight, background = "#e1e1e1")
```
