---
title: "Power Analysis"
output:
  html_document:
    theme: united
    toc: true
    toc_float: true
    number_sections: false
---

```{r setup, include=FALSE}
# Basic knit settings
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.retina = 3,
  fig.path = "figs/"
)

library(tidyverse)
library(cbcTools)
```

First, define the attributes and levels:

```{r}
profiles <- cbc_profiles(
  price       = c(15, 20, 25), # Price ($1,000)
  fuelEconomy = c(20, 25, 30), # Fuel economy (mpg)
  accelTime   = c(6, 7, 8),    # 0-60 mph acceleration time (s)
  powertrain  = c('Gasoline', 'Electric')
)
```

# Random design

Make a full-factorial (randomized) design:

```{r}
design_rand <- cbc_design(
  profiles = profiles,
  n_resp   = 500, # Number of respondents
  n_alts   = 3,   # Number of alternatives per question
  n_q      = 6    # Number of questions per respondent
)

head(design_rand)
```

Simulate choices

```{r}
data_rand <- cbc_choices(
    design = design_rand,
    obsID = "obsID"
)
```

Run power analysis

```{r}
power_rand <- cbc_power(
    nbreaks = 10,
    data    = data_rand,
    pars    = c("price", "fuelEconomy", "accelTime", "powertrain"),
    outcome = "choice",
    obsID   = "obsID"
)

head(power_rand)
tail(power_rand)
```

Here is a summary of the standard errors for each sample size:

```{r}
ggplot(power_rand) +
  geom_hline(yintercept = 0.05, color = "red", linetype = 2) +
  geom_point(aes(x = sampleSize, y = se, color = coef)) +
  expand_limits(y = 0) +
  scale_y_continuous(limits = c(0, 0.125)) +
  theme_bw() + 
  labs(
    x = "Sample size", 
    y = "Standard error", 
    color = "Coefficient"
  )
```


# D-efficient design

Make a D-efficient design:

```{r}
priors <- list(
  price       = 0,
  fuelEconomy = 0,
  accelTime   = 0,
  powertrain  = 0
)

design_deff <- cbc_design(
  profiles  = profiles,
  n_resp    = 500, # Number of respondents
  n_alts    = 3, # Number of alternatives per question
  n_q       = 6, # Number of questions per respondent
  n_start   = 10, 
  n_blocks  = 1,
  priors = priors
)

head(design_deff)
```

Simulate choices

```{r}
data_deff <- cbc_choices(
    design = design_deff,
    obsID  = "obsID",
    priors = priors
)

head(data_deff)
```

Run power analysis

```{r}
power_deff <- cbc_power(
    nbreaks = 10,
    data    = data_deff,
    pars    = c("price", "fuelEconomy", "accelTime", "powertrain"),
    outcome = "choice",
    obsID   = "obsID"
)

head(power_deff)
tail(power_deff)
```

Here is a summary of the standard errors for each sample size:

```{r}
ggplot(power_deff) +
  geom_hline(yintercept = 0.05, color = "red", linetype = 2) +
  geom_point(aes(x = sampleSize, y = se, color = coef)) +
  expand_limits(y = 0) +
  scale_y_continuous(limits = c(0, 0.125)) +
  theme_bw() + 
  labs(
    x = "Sample size", 
    y = "Standard error", 
    color = "Coefficient"
  )
```

